### ISSUE TITLE
Persistance layer

### ISSUE THREAD

**Issue by PEZO19** [TSOptics/optics#2]
Hi there!

Your state management solution seems really cool! Can you please share your ideas about a persistance layer?

**Comment by VincentQuillien** [comment]
Hi !
You can add persistance to any optic this way:

```ts
const onValue = createState(initialValue).derive(
  (value) => {
    const storedValue = JSON.parse(localStorage.getItem(key));
    return storedValue ?? value;
  },
  (newValue) => {
    localStorage.setItem(key, JSON.stringify(newValue));
    return newValue;
  },
);
```

For now it's not possible with asynchronous Api's like RN AsyncStorage, but I'm working on an `AsyncOptic` primitive with native support for promises.
I'll take the time to properly document all of that.

**Comment by PEZO19** [comment]
Thanks a lot!
