### ISSUE TITLE
When `focusOn` is called on undefined, `.get()` returns an optic.

### ISSUE THREAD

**Issue by cwstra** [TSOptics/optics#21]
Issue's more or less what it says on the tin; aside from being a bit weird, this disagrees with what TS infers for potentially-undefined base values.

```typescript
import {focusOn} from '@optics/data'

const fn = (value: {a: string} | undefined): string | undefined => 
  focusOn(value).a.get();

// Prints out a DataOpticImpl
console.log(fn(undefined))
```

**Comment by VincentQuillien** [comment]
Hi @cwstra,

Nice catch, thanks for the heads up !

Just fixed in v0.5.1.
